[project]
name = "ogb-arxiv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ebad-urRehman", email = "ibad.rashid.research@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.2",
    "ogb>=1.3.6",
    "torch>=2.14.0",
    "torch-geometric>=2.8.0.post1",
]

[project.scripts]
ogb-arxiv = "ogb_arxiv:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
